### ISSUE TITLE
Age armor tests and RFC7468, which textual encoding to use?

### ISSUE THREAD

**Issue by v3rm0n** [C2SP/CCTV#8]
I'm trying to add armored support to [dage](https://github.com/Producement/dage) and I'm struggling to understand which textual encoding of [RFC7468](https://datatracker.ietf.org/doc/html/rfc7468#section-3) should be supported, because the test vectors seem to allow whitespace before and after which would imply lax encoding, but at the same time, whitespace in armored body is not allowed so it can't be the lax encoding...

**Comment by FiloSottile** [comment]
It's the strict encoding, but we chose to explicitly allow whitespace before and after the PEM block, because it's pretty hard to debug having copy-pasted some extra spaces.

> age implementations SHOULD reject non-canonical ASCII armor encodings except for whitespace before and after the PEM block, and MAY choose to accept both LF and CRLF line endings.

https://github.com/C2SP/C2SP/blob/main/age.md#ascii-armor
